[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas reporting
gas_reports = ["*"]

# Test configuration
verbosity = 2

# RPC endpoints
[rpc_endpoints]
hyperliquid = "https://rpc.hyperliquid.xyz/evm"
local = "http://127.0.0.1:8545"

# Fork testing profile
[profile.fork]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
gas_reports = ["*"]
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
